export default [
  {
    jour: "Lundi",
    lieu: "Ecole de Marcelly",
    debut: "17:15",
    fin: "18:45",
    niveau: "Débutant",
    age: "10 - 15 ans",
    cours: "JUNIOR II",
  },
  {
    jour: "Lundi",
    lieu: "Collège de Candolle",
    debut: "18:00",
    fin: "19:30",
    niveau: "Avancé",
    age: "10 - 15 ans",
    cours: "JUNIOR III",
  },
  {
    jour: "Mercredi",
    lieu: "Ecole de Marcelly",
    debut: "14:00",
    fin: "15:30",
    niveau: "Tous",
    age: "- 10 ans",
    cours: "JUNIOR I",
  },
  {
    jour: "Jeudi",
    lieu: "Collège de Candolle",
    debut: "18:15",
    fin: "19:45",
    niveau: "Tous",
    age: "15 - 18 ans",
    cours: "JUNIOR IV",
  },
]
